# -*- coding: utf-8 -*-
"""Capstone Project 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrQA8pV9Qa17UYZn1FogITcjW3MLuzrA
"""

#Project 2

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

df = pd.read_csv('/content/drive/MyDrive/OnlineRetail (3).csv', encoding="ISO-8859-1")
df.head()

df=df[['CustomerID', 'InvoiceNo', 'StockCode','Quantity', 'UnitPrice','Description', 'InvoiceDate','Country']]
df.head()

df['Country'].unique()

TotalAmount = df['Quantity'] * df['UnitPrice']

df.insert(loc=5, column = 'TotalAmount', value=TotalAmount)

df.head()

new_df = df[['CustomerID', 'InvoiceNo', 'StockCode', 'Quantity','TotalAmount', 'InvoiceDate', 'Country']]
new_df2 = df.copy()
new_df.head()

new_df2.head()

country_price = new_df.groupby('Country')['Quantity'].sum().sort_values(ascending = False)
country_price

country_totalAmount = new_df.groupby('Country')['TotalAmount'].sum().sort_values(ascending=False)
country_totalAmount

country_price[:5].plot(kind='bar')

country_price[33:].plot(kind='bar')

new_df['Year'] = pd.DatetimeIndex(new_df['InvoiceDate']).year
new_df['Mon'] = pd.DatetimeIndex(new_df['InvoiceDate']).month
new_df['month'] = pd.DatetimeIndex(new_df['InvoiceDate']).month_name
new_df.groupby(['Mon', 'Year'])['TotalAmount'].sum().plot(kind='bar', title = 'Sales Month Wise')

cus_id =  pd.DataFrame(new_df.groupby('Country')['CustomerID'].count().sort_values(ascending = False))
cus_id[:5].plot(kind='bar', title='Country with most customers')

cus_id[-5:].plot(kind='bar', title='Least customers for country')

